
service: gather-bot-engine

#AWS_CLIENT_TIMEOUT !!
provider:
  name: aws
  runtime: python2.7
  cfLogs: true

functions:
  engine:
    handler: handler.run
    events:
      - s3:
          bucket: gather-bot-bucket
          event: s3:ObjectCreated:*
