
service: gather-bot

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs4.3

functions:
  slackEvents:
    handler: handler-slack.events
    events:
      - http:
          path: events
          method: post
  slackCommands:
    handler: handler-slack.commands
    events:
      - http:
          path: command/{name}
          method: post
  uploadFile:
    handler: handler-slack.uploadFile
    events:
      - s3:
          bucket: gather-bot-bucket
          event: s3:ObjectCreated:*
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
